### ISSUE TITLE
在线编辑的文档是存在本地还是远程服务器的？

### ISSUE THREAD

**Issue by huanghb1021** [jserme/mahua#24]
http://mahua.jser.me/ 挂了，工作记录，加班记录全部没了。
加班加到吐血，全没了，一个月4，50个小时。

**Comment by huanghb1021** [comment]
研究了老半天代码 终于知道数据怎么找回了。但是我不告诉你们怎么找回

**Comment by jserme** [comment]
太抱歉了，这个是纯本地的，没有存远程服务器，可以加我微信 jserme 详聊一下
