### ISSUE TITLE
有没有自动生成目录功能

### ISSUE THREAD

**Issue by zaobao** [jserme/mahua#5]
如题

**Comment by wangchongsen** [comment]
生成啥的目录

**Comment by zaobao** [comment]
就是在文章开头按照标题自动生成索引，markdown有没有自带这种功能我也不知道
有些编辑器支持在前面加[TOC]就可以根据标题生成索引，点击就可以到文章中相应的地方，就像维基百科那种自动生成的目录

**Comment by jserme** [comment]
这个项目已经不维护了，抱歉

这个功能已经考虑加入到mahua2里了
